### ISSUE TITLE
`sources` and `profileIds` missing from `useExplorePublications` request 

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#490] opened 2023-08-11 13:22 UTC
**Describe the bug**
`sources` and `profileIds` missing from `useExplorePublications` request 

react-web 1.3.0-next

**Comment by cesarenaldi** [comment] 2023-08-11 13:38
I am going to add `profileIds` in the next release.

Regarding `sources`... I can see it working in my example. Are you providing it as part of the `LensConfig`?

**Comment by moesalih** [comment] 2023-08-11 13:39
No i'm not providing it part of LensConfig. I only want to provide it to one useExplorePublications request, not the entire sdk.

**Comment by cesarenaldi** [comment] 2023-08-11 14:18
Got it.

Overriding sources on a call base is a change we had planned already. It will definitely be part of Lens SDK v2 but cannot guarantee we can work on it earlier.

I would need to get back to you on this next week.

**Comment by moesalih** [comment] 2023-08-11 19:23
@cesarenaldi just noticed that `useExplorePublications` is also missing the `noRandomize` option

**Comment by cesarenaldi** [comment] 2023-08-14 08:12
@moesalih adding `noRandomize` and `sources` override option. Just noticing that `explorePublications` does not accept `profileIds`.

**Comment by cesarenaldi** [comment] 2023-08-14 08:56
`noRandomize ` and `sources` override option is now available in `1.3-next.8` can you please update and confirm works as intended so we can close this issue?

**Closed** 2023-08-14 18:58 UTC
