### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by jsonpreet** [lens-protocol/lens-sdk#422] opened 2023-07-16 11:44 UTC
**Describe the bug**
In the notifications hook, 
1. highSignalFilter is not supported, so it’s always returning filtered, not all notifications.
2. Collect notifications show really old notifications from 2 months ago
3. Mirror notification post no getting correct typename, It won't return mirrorOf data.

**If using the React bindings, what is the essence of your React app?**
- [x] React Web App

**Version of the packages you are using**
1.2.1

**Comment by cesarenaldi** [comment] 2023-07-16 12:44
hey @jsonpreet thank you for reporting this.

I'll schedule `highSignalFilter` to the next release.

Regarding point 2. I cannot think of a way that this could be caused by the SDK. Can you please provide more details about the Profile you are using and what are you expectations in terms of notifications? Do you see something different on another Lens app?

Regarding 3. The `publication` edge has been designed to return `Post` or `Comment`. It does not return `Mirror` type, but only the mirrored publication.
<img width="593" alt="image" src="https://github.com/lens-protocol/lens-sdk/assets/3353250/bba0fa25-c0be-40fb-b96e-9b4940eb86ec">

**Comment by jsonpreet** [comment] 2023-07-17 05:46
![Screenshot 2023-07-17 111209](https://github.com/lens-protocol/lens-sdk/assets/26606638/14d1dc73-2229-4152-9551-f94531ac02a9)

![Screenshot 2023-07-17 111218](https://github.com/lens-protocol/lens-sdk/assets/26606638/d46986af-9a24-4bf0-b2e5-98c120b149a3)

![Screenshot 2023-07-17 101331](https://github.com/lens-protocol/lens-sdk/assets/26606638/298e8e16-db53-4880-8ff7-e38d616a6231)

Look at three screenshots,

1st from Notifications - It show Pinsta mirrored a post
2nd When I click on Notification it redirect to that publication
3rd is When I checked in my profile it show Pinsta mirrored a post and in the publication detail it show my Avatar and name

But it won't happened in 2nd screenshot

**Comment by cesarenaldi** [comment] 2023-07-17 07:22
@jsonpreet can you please clarify one thing... are the screenshots related to the "Collect notifications show really old notifications from 2 months ago" issue you mentioned?

Regarding the screenshot... I don't see any issue. Notifications listing is different from Profile activities listing. They are different query with different focus. Notification highlights "events in time". The primary entity returned are notificaitons which might be in a 1:1, 1:N relationship with other entities. While profile activities are created out of `profiles` query, so it depends on the app builder on what they retrieve and render them.

Please let me know if I missed something.

**Comment by jsonpreet** [comment] 2023-07-17 07:28
Sir that screenshots related to mirrored notification issue

**Comment by cesarenaldi** [comment] 2023-07-17 07:49
Got it. So my previous comment on the Mirror notification issue still stands:

> The publication edge has been designed to return Post or Comment. It does not return Mirror type, but only the mirrored publication.

With reference to the GQL (which in turns is the same TS/JS object returned for this notification type):

![image](https://github.com/lens-protocol/lens-sdk/assets/3353250/57fa4ed9-b908-4030-8241-9b3bf04bfc22)

The Profile that mirrored the Publication is `notification.profile`, the mirrored Publication is `notification.publication`.

`notification.publication` cannot be a `Mirror` so it does not have a `mirrorOf`. But `publication` IS what you expected from `mirrorOf`.

**Comment by moesalih** [comment] 2023-07-17 15:37
hi @cesarenaldi . the issue he is that the `notification.publication` returned in `NewMirrorNotification` is actually the new mirror publication and not the original publication being mirrored. here's an example:

```
notificationId: mirrored-post-0xacaf-0x2b9a-0x03a1-DA-b42e8dfa
new mirror publication: 0xacaf-0x4bd8-DA-f8bc7dd3
original mirrored publication: 0x2b9a-0x03a1-DA-b42e8dfa
```
<img width="1068" alt="Screenshot 2023-07-17 at 11 21 42 AM" src="https://github.com/lens-protocol/lens-sdk/assets/2164738/7a5bbc3c-66ad-40ac-865e-cf893387cb32">
<img width="529" alt="Screenshot 2023-07-17 at 11 22 42 AM" src="https://github.com/lens-protocol/lens-sdk/assets/2164738/5577c139-4766-4561-ac91-6f267a6760d4">
<img width="402" alt="Screenshot 2023-07-17 at 11 35 57 AM" src="https://github.com/lens-protocol/lens-sdk/assets/2164738/1ba79873-6070-4799-8d33-bea41ef916d8">

<img width="608" alt="Screenshot 2023-07-17 at 11 23 24 AM" src="https://github.com/lens-protocol/lens-sdk/assets/2164738/29eff74d-41d9-4921-80ce-610acc2be71b">
<img width="411" alt="Screenshot 2023-07-17 at 11 36 07 AM" src="https://github.com/lens-protocol/lens-sdk/assets/2164738/ac7bab1b-cfe2-41c0-a6eb-4c8c7314d10c">


- Zelda mirrored my post (id 0x2b9a-0x03a1-DA-b42e8dfa)
- first screenshot shows the notification, the `publication` property has the new mirror publication (0xacaf-0x4bd8-DA-f8bc7dd3) but its being misclassified as a post so we cant get the original publication.
- this causes further issues because now the internal cache of the sdk had that new mirror publication (0xacaf-0x4bd8-DA-f8bc7dd3) classified as a post so anytime its queried by other hooks like `usePublication` then it's being returned as a post and that's why it gets misrendered by the app. but if we do a full refreh on the post page for 0xacaf-0x4bd8-DA-f8bc7dd3. then a fresh api query for that spefici publication returns the correct classification as Mirror.

**Comment by moesalih** [comment] 2023-07-17 15:39
for 'Collect notifications show really old notifications from 2 months ago' please ignore that, it was actually just the `highSignalFilter` not being respected so recent notifications weren't showing up.

**Comment by cesarenaldi** [comment] 2023-07-17 16:44
@moesalih I think you are onto something. Seems an API issue, I'll relay this internally and will let you know.

**Comment by cesarenaldi** [comment] 2023-07-19 18:55
@moesalih I did run a query (see screenshot below) to double check the data point you gave me
<img width="1581" alt="image" src="https://github.com/lens-protocol/lens-sdk/assets/3353250/5a551c36-5002-45cd-a51c-14ada9e7cebc">

Regarding what you wrote:
> the issue here is that the notification.publication returned in NewMirrorNotification is actually the new mirror publication and not the original publication being mirrored.

Unless we are using different terminology I don't have evidence of this issue. My query above is coherent with the screenshot you gave us.

The `publication` property in the `NewMirrorPublication` is the original publication (a Post in this case).

Am I missing something?

**Comment by moesalih** [comment] 2023-07-19 19:54
hi @cesarenaldi , the screenshot you show is correct because when you just query the api for `0xacaf-0x4bd8-DA-f8bc7dd3` then it'll correctly return it as a mirror.

but your second point is not correct. The `publication` property in the `NewMirrorPublication` is NOT the original post publication. I've confirmed this multiple times. and you can see that in the first screenshot i shared:
<img width="1068" alt="Screenshot 2023-07-17 at 11 21 42 AM" src="https://github.com/lens-protocol/lens-sdk/assets/2164738/03d531c0-83f9-4ee3-89e5-619b21b04ed8">

This shows the  `NewMirrorPublication` object i'm getting, and in it the publication property returned is `0xacaf-0x4bd8-DA-f8bc7dd3` which is the new mirror, but it's being returned as a post. The correct behavior would be to return `0x2b9a-0x03a1-DA-b42e8dfa` under publication there.

**Comment by cesarenaldi** [comment] 2023-07-20 07:16
@moesalih my bad... you are right. The `publication.id` is wrong there. Wondering if this is an issue with new Momoka mirrors. Will ask @joshstevens19 at the first opportunity.

**Comment by cesarenaldi** [comment] 2023-07-20 11:57
Regarding `highSignalFilter`.... we just pushed a pre-release under `@lens-protocol/react-web@1.3.0-next.0` and `@lens-protocol/react@1.3.0-next.0` tags. Can you please try to see if it match your notifications expectations?

**Comment by moesalih** [comment] 2023-07-20 14:46
> @moesalih my bad... you are right. The `publication.id` is wrong there. Wondering if this is an issue with new Momoka mirrors. Will ask @joshstevens19 at the first opportunity.

I don't believe this is related to momoka, because i actually remember reporting this exact issue on the lens discord late last year when I first started building the buttrfly mobile app. but i dont think the report message was seen by the dev team so it was never fixed.

And this hasn't been a problem with the mobile app because I dont do any caching there.

**Comment by cesarenaldi** [comment] 2023-07-20 16:32
I see. Why you think this is cache related?


I raise a ticket internally. I'll let you know when prioritized.

**Comment by moesalih** [comment] 2023-07-20 16:50
> I see. Why you think this is cache related?
> 
> I raise a ticket internally. I'll let you know when prioritized.

As I mentioned in my first message. The fact that NewMirrorPublication is returning the mirror publication as a post causes further issues because now the internal cache of the sdk has that new mirror publication (0xacaf-0x4bd8-DA-f8bc7dd3) classified as a post so anytime it's queried by other hooks like usePublication then it's being returned as a post instead of mirror and that's why it gets misrendered by the app.

The mobile app doesn't do any cache, so requesting publication 0xacaf-0x4bd8-DA-f8bc7dd3 will always do a fresh request with proper api response.

**Comment by cesarenaldi** [comment] 2023-07-20 17:15
I see what you mean. Thank you for the explainer.

**Comment by cesarenaldi** [comment] 2023-08-04 14:14
@jsonpreet and @moesalih if I understand correctly of this thread the only outstanding issue is the fact `NewMirrorPublication` erroneously returns a Mirror publication as it where to be a Post.

This is definitely an API bug which I reported and it's tracked.

As you might imagine we are in the thick of Lens v2 changes (API and SDK). In the new GQL schema we designed this week the notifications will get an overhaul refactoring and this issue will be resolved at the root.

Can you please help me understand how problematic is this for your apps in the short term (1 month or so)?

**Comment by moesalih** [comment] 2023-08-04 14:47
hi @cesarenaldi this is not a big problem for Buttrfly, we can definitely wait a month until the v2 apis are out. thanks.

**Comment by cesarenaldi** [comment] 2023-08-04 15:40
Let me clarify one thing I mentioned short term without implying Lens v2 API will be available in a month time. Surely we have aggressive internal timelines but don't mean to mislead you here (I amended my previous message).

I guess I am saying. Can you wait for Lens v2 API? Can you have workarounds in place until then?

**Comment by moesalih** [comment] 2023-08-04 15:55
@cesarenaldi yeah i can wait for v2 api for this fix. For a workaround, I'm hoping the change you mentioned in another issue (https://github.com/lens-protocol/lens-sdk/issues/419#issuecomment-1642625446) would be enough to avoid this issue in the buttrfly ui:

> One strategy is the one that applies to "read hooks" that return a single entity (e.g. usePublication, useProfile). For these hooks in case of full re-render, the data cached will be used to show immediate content to the consumer while under the hook a network request will fire to update the data. Once such request is completed the data will be updated immediately.

with this change, when going from the notifications screen to a mirror, the sdk with return the the incorrect cached version of the publication, but then do a request and return the correct full data from the api

am i understanding this correctly? any idea on when this change will be released?

**Comment by cesarenaldi** [comment] 2023-08-07 13:56
I don't know if that fix will affect here. Unfortunately this is an API issue where the API returns a mirror ID as `Post`. The SDK trust this to be correct and that's it.

**Comment by moesalih** [comment] 2023-08-07 16:58
> I don't know if that fix will affect here. Unfortunately this is an API issue where the API returns a mirror ID as `Post`. The SDK trust this to be correct and that's it.

@cesarenaldi Yes I understand, but wouldn't subsequent calls to `usePublication` with that mirror ID cause the SDK to do a fresh request from the `publication` endpoint which will return the correct data? That's what I'm understanding from the below text

> One strategy is the one that applies to "read hooks" that return a single entity (e.g. usePublication, useProfile). For these hooks in case of full re-render, the data cached will be used to show immediate content to the consumer while under the hook a network request will fire to update the data. Once such request is completed the data will be updated immediately.

**Comment by cesarenaldi** [comment] 2023-08-07 17:16
Oh yeah, I understand now... the workaround would be to take the Id from the mirror notification and feed it into the `usePublication`. Yes, I think you are right. Currently working on an improvement for `useCreateProfile` then that fix is the next in the line. Expect to have a version on a `next` release this week.

**Comment by cesarenaldi** [comment] 2023-08-08 20:15
@moesalih yeah, an oversight on my side in staging the files. Fix here: https://github.com/lens-protocol/lens-sdk/pull/478

Will be merged and released this week.

**Comment by cesarenaldi** [comment] 2023-08-10 17:15
> @cesarenaldi yeah i can wait for v2 api for this fix. For a workaround, I'm hoping the change you mentioned in another issue ([#419 (comment)](https://github.com/lens-protocol/lens-sdk/issues/419#issuecomment-1642625446)) would be enough to avoid this issue in the buttrfly ui:
> 
> > One strategy is the one that applies to "read hooks" that return a single entity (e.g. usePublication, useProfile). For these hooks in case of full re-render, the data cached will be used to show immediate content to the consumer while under the hook a network request will fire to update the data. Once such request is completed the data will be updated immediately.
> 
> with this change, when going from the notifications screen to a mirror, the sdk with return the the incorrect cached version of the publication, but then do a request and return the correct full data from the api
> 
> am i understanding this correctly? any idea on when this change will be released?

The fix. for issue #419 will be released soon: https://github.com/lens-protocol/lens-sdk/pull/485

**Comment by cesarenaldi** [comment] 2023-08-14 08:52
@moesalih can you please confirm `highSignalFilter` now works as expected?

Also since `1.3-next.6` we have the solution for https://github.com/lens-protocol/lens-sdk/issues/419... can you please confirm the workaround for the `NewMirrorNotification` works so we can close this thread?

**Comment by moesalih** [comment] 2023-08-14 19:02
Both work.

**Comment by cesarenaldi** [comment] 2023-08-14 19:58
Thank you for checking and suggesting the workaround details. We can use this issue as reference until fully sorted in Lens API v2.

**Closed by cesarenaldi** 2023-08-14 19:58 UTC
