### ISSUE TITLE
Not possible to toggle options in useComments

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#476] opened 2023-08-08 13:45 UTC
**Describe the bug**
It's currently not possible to toggle options like `commentsOfOrdering` and `commentsRankingFilter`  in `useComments`. can this be supported? 
Edit: in fact, these attributes don't seem to be passed to the actual graphql query at all.

**Expected behaviuor**
i expect those options to be toggled so the user can toggle the order of comments in the ui. 

**If using the React bindings, what is the essence of your React app?**
react-web 1.2.2 and 1.3.0-next.4

**Comment by cesarenaldi** [comment] 2023-08-10 07:37
They can easily be added.

**Comment by cesarenaldi** [comment] 2023-08-14 08:53
@moesalih this is now available in `1.3-next.8` can you please update and confirm works as intended so we can close this issue?

**Closed** 2023-08-14 19:01 UTC
