### ISSUE TITLE
`profileIds` in usePublications and useProfiles

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#489] opened 2023-08-11 13:12 UTC
**Describe the bug**
When doing a request with `profileIds` in `usePublications` and `useProfiles`, the results are cached and no new values for `profileIds` can be requested on those hooks anymore.

**Expected behaviuor**
I should be able to call `usePublications` and `useProfiles` with different arrays of profileIds and get proper results each time.

react-web 1.3.0-next

**Comment by cesarenaldi** [comment] 2023-08-11 13:19
@moesalih are you able to provide a little snippet of code that showcase the way you change `profileIds`?

**Comment by moesalih** [comment] 2023-08-11 13:28
i'm not dynamically changing the profileIds in the same mounted instance of the hook. I meant using usePublications with some profileIds, and then going to another page that also uses usePublications with another set of profileIds, the seconds request won't actually fire and will just return the cached results for the first previous request

**Comment by cesarenaldi** [comment] 2023-08-11 13:32
Oh, I see what's going on. Will let you know when a fix is available.

**Comment by cesarenaldi** [comment] 2023-08-14 08:55
@moesalih this is now available in `1.3-next.8` can you please update and confirm works as intended so we can close this issue?

**Closed** 2023-08-14 18:37 UTC
