### ISSUE TITLE
`name` missing from useCreatePost and useCreateComment

### ISSUE THREAD

**Issue by moesalih** [lens-protocol/lens-sdk#482] opened 2023-08-09 15:03 UTC
**Describe the bug**

It's not currently possible to set `name` in metadata when posting. This is required for normal posts, not just collected NFTs.

`name` is a standard property commonly used by most popular lens apps to set the name or title of a post:
- Video posts include this property, and this for example gets displayed for video titles on lenstube.
- Audio posts include this property, and this gets displayed in all lens apps that show and play music (lenster, orb, buttrfly, ...)
- Text posts too have a title which usually defaults to the first line of the post, but can be customized for example in buttrfly. This title does get displayed in some areas of the UI on various apps (for example in stats, or collecting flow before the post is actually collected)

react-web 1.3.0-next

**Comment by cesarenaldi** [comment] 2023-08-09 15:24
No problem.

**Comment by cesarenaldi** [comment] 2023-08-14 08:55
@moesalih this is now available in `1.3-next.8` can you please update and confirm works as intended so we can close this issue?

**Closed** 2023-08-15 14:41 UTC
